from datetime import datetime

datos_demo = [
            # 🇨🇱 CHILE (5 registros - 2 en el mismo mes/año, otros en otras fechas para variar temporalidad)
            {"sexo": 1, "grupo_edad": 2, "grupo_racial": 1, "nivel_educativo": 3, "categoria_ingresos": 1,
            "altura": 1.75, "peso": 80.5, "presion_alta": 1, "colesterol_alto": 0, "control_colesterol": 1,
            "bmi": 25.2, "fumo_100_cigs": 0, "historial_acv": 2, "historial_cardiaco": 1, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 2, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 4, "salud_general": 3, "dias_mala_salud_fisica": 2, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Sudamerica", "pais": "Chile", "region": "Coquimbo", "created_at": datetime(2023, 5, 15)},
            {"sexo": 2, "grupo_edad": 3, "grupo_racial": 1, "nivel_educativo": 4, "categoria_ingresos": 2,
            "altura": 1.65, "peso": 70.0, "presion_alta": 0, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 22.5, "fumo_100_cigs": 1, "historial_acv": 2, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 1, "actividad_300min": 1, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 3, "dias_mala_salud_mental": 1,
            "diabetes_bin": 1, "continente": "Sudamerica", "pais": "Chile", "region": "Santiago", "created_at": datetime(2023, 5, 21)},
            {"sexo": 1, "grupo_edad": 4, "grupo_racial": 1, "nivel_educativo": 3, "categoria_ingresos": 2,
            "altura": 1.80, "peso": 85.3, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 26.3, "fumo_100_cigs": 0, "historial_acv": 2, "historial_cardiaco": 1, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 2, "actividad_muscular": 1, "frecuencia_frutas": 4,
            "frecuencia_verduras": 4, "salud_general": 2, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Sudamerica", "pais": "Chile", "region": "Valparaíso", "created_at": datetime(2023, 9, 10)},
            {"sexo": 2, "grupo_edad": 1, "grupo_racial": 1, "nivel_educativo": 1, "categoria_ingresos": 1,
            "altura": 1.60, "peso": 55.0, "presion_alta": 0, "colesterol_alto": 0, "control_colesterol": 1,
            "bmi": 21.5, "fumo_100_cigs": 1, "historial_acv": 1, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 2, "actividad_300min": 2, "actividad_muscular": 2, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Sudamerica", "pais": "Chile", "region": "Biobío", "created_at": datetime(2024, 1, 5)},
            {"sexo": 1, "grupo_edad": 3, "grupo_racial": 2, "nivel_educativo": 2, "categoria_ingresos": 3,
            "altura": 1.72, "peso": 78.0, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 25.1, "fumo_100_cigs": 1, "historial_acv": 2, "historial_cardiaco": 2, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 1, "actividad_muscular": 1, "frecuencia_frutas": 2,
            "frecuencia_verduras": 3, "salud_general": 2, "dias_mala_salud_fisica": 3, "dias_mala_salud_mental": 2,
            "diabetes_bin": 1, "continente": "Sudamerica", "pais": "Chile", "region": "La Araucanía", "created_at": datetime(2024, 3, 15)},

            # 🇵🇪 PERÚ (2 registros en diferentes fechas/años para variar temporalidad)
            {"sexo": 1, "grupo_edad": 2, "grupo_racial": 3, "nivel_educativo": 3, "categoria_ingresos": 1,
            "altura": 1.68, "peso": 72.0, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 25.5, "fumo_100_cigs": 0, "historial_acv": 1, "historial_cardiaco": 2, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 2, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 3, "dias_mala_salud_mental": 2,
            "diabetes_bin": 1, "continente": "Sudamerica", "pais": "Perú", "region": "Lima", "created_at": datetime(2023, 7, 8)},
            {"sexo": 2, "grupo_edad": 1, "grupo_racial": 3, "nivel_educativo": 1, "categoria_ingresos": 1,
            "altura": 1.55, "peso": 60.3, "presion_alta": 0, "colesterol_alto": 0, "control_colesterol": 1,
            "bmi": 20.9, "fumo_100_cigs": 1, "historial_acv": 2, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 2, "actividad_300min": 1, "actividad_muscular": 2, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Sudamerica", "pais": "Perú", "region": "Cusco", "created_at": datetime(2024, 2, 12)},

            # 🇪🇸 ESPAÑA (3 registros en diferentes fechas/años para variar temporalidad.)
            {"sexo": 1, "grupo_edad": 2, "grupo_racial": 1, "nivel_educativo": 3, "categoria_ingresos": 3,
            "altura": 1.76, "peso": 83.1, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 26.8, "fumo_100_cigs": 1, "historial_acv": 1, "historial_cardiaco": 2, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 2, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 3, "dias_mala_salud_mental": 1,
            "diabetes_bin": 1, "continente": "Europa", "pais": "España", "region": "Madrid", "created_at": datetime(2023, 6, 18)},
            {"sexo": 2, "grupo_edad": 3, "grupo_racial": 1, "nivel_educativo": 3, "categoria_ingresos": 2,
            "altura": 1.69, "peso": 69.5, "presion_alta": 0, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 24.3, "fumo_100_cigs": 0, "historial_acv": 1, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 1, "actividad_300min": 2, "actividad_muscular": 1, "frecuencia_frutas": 2,
            "frecuencia_verduras": 3, "salud_general": 2, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Europa", "pais": "España", "region": "Barcelona", "created_at": datetime(2023, 9, 27)},
            {"sexo": 1, "grupo_edad": 1, "grupo_racial": 2, "nivel_educativo": 2, "categoria_ingresos": 1,
            "altura": 1.80, "peso": 75.0, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 25.5, "fumo_100_cigs": 1, "historial_acv": 2, "historial_cardiaco": 1, "dificultad_caminar": 2,
            "actividad_fisica": 1, "actividad_300min": 1, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 3, "dias_mala_salud_mental": 2,
            "diabetes_bin": 1, "continente": "Europa", "pais": "España", "region": "Sevilla", "created_at": datetime(2024, 4, 3)},

            # 🇵🇹 PORTUGAL (2 registros en diferentes fechas/años para variar temporalidad.)
            {"sexo": 1, "grupo_edad": 2, "grupo_racial": 1, "nivel_educativo": 3, "categoria_ingresos": 2,
            "altura": 1.73, "peso": 72.5, "presion_alta": 1, "colesterol_alto": 1, "control_colesterol": 1,
            "bmi": 24.5, "fumo_100_cigs": 1, "historial_acv": 1, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 1, "actividad_300min": 1, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 3, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 1, "continente": "Europa", "pais": "Portugal", "region": "Lisboa", "created_at": datetime(2023, 8, 12)},
            {"sexo": 2, "grupo_edad": 1, "grupo_racial": 2, "nivel_educativo": 2, "categoria_ingresos": 1,
            "altura": 1.65, "peso": 57.3, "presion_alta": 0, "colesterol_alto": 0, "control_colesterol": 1,
            "bmi": 21.0, "fumo_100_cigs": 1, "historial_acv": 1, "historial_cardiaco": 1, "dificultad_caminar": 1,
            "actividad_fisica": 1, "actividad_300min": 1, "actividad_muscular": 1, "frecuencia_frutas": 3,
            "frecuencia_verduras": 3, "salud_general": 2, "dias_mala_salud_fisica": 1, "dias_mala_salud_mental": 1,
            "diabetes_bin": 0, "continente": "Europa", "pais": "Portugal", "region": "Porto", "created_at": datetime(2024, 3, 25)}
        ]